### ISSUE TITLE
Yeoman error in exercise 4 part A

### ISSUE THREAD

**Issue by pdominique** [SAP-samples/cloud-cap-walkthroughs#5]
Step Part A 4 c doesn't work: 

```
user: bookstore $ yo
? 'Allo! What would you like to do? Fiori Application

Make sure you are in the directory you want to scaffold into.
This generator can also be run with: yo fiori-application

SAP Fiori Application Generator
? Specify a path to the root project /home/user/projects/cloud-cap-samples/packages/bookstore
? Specify a path to the SAP Fiori application /home/user/projects/cloud-cap-samples/packages/bookstore/app

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, scandir '/extbin/generators/ui5-generators'
    at Object.readdirSync (fs.js:790:3)
    at TemplateExplorationGenerator._getFilteredTemplates (/extbin/generators/lib/node_modules/generator-fiori-application/node_modules/generator-templates-exploration/generators/app/index.js:90:21)
    at TemplateExplorationGenerator.<anonymous> (/extbin/generators/lib/node_modules/generator-fiori-application/node_modules/generator-templates-exploration/generators/app/index.js:48:42)
    at Generator.next (<anonymous>)
    at /extbin/generators/lib/node_modules/generator-fiori-application/node_modules/generator-templates-exploration/generators/app/index.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/extbin/generators/lib/node_modules/generator-fiori-application/node_modules/generator-templates-exploration/generators/app/index.js:3:12)
    at TemplateExplorationGenerator.initializing (/extbin/generators/lib/node_modules/generator-fiori-application/node_modules/generator-templates-exploration/generators/app/index.js:44:16)
    at Object.<anonymous> (/extbin/generators/lib/node_modules/generator-fiori-application/node_modules/yeoman-generator/lib/index.js:424:27)
    at /extbin/generators/lib/node_modules/generator-fiori-application/node_modules/run-async/index.js:25:25
Emitted 'error' event at:
    at Immediate.setImmediate (/extbin/generators/lib/node_modules/generator-fiori-application/node_modules/yeoman-generator/lib/index.js:433:22)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
user: bookstore $ 
```

**Comment by pdominique** [comment]
This issue is fixed: https://blogs.sap.com/2019/10/15/showcasing-sap-business-application-studio-the-next-generation-of-sap-web-ide/comment-page-1/#comment-477111
