### ISSUE TITLE
yo Fiori Application generator doesn't work on Canary

### ISSUE THREAD

**Issue by ivanmir** [SAP-samples/cloud-cap-walkthroughs#8]
I've been trying to use yo to create an UI for my CAP project, but it gives me the following error:

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, scandir '/extbin/generators/ui5-generators'
    at Object.readdirSync (fs.js:790:3)
    at TemplateExplorationGenerator._getFilteredTemplates (/extbin/generators/lib/node_modules/generator-fiori-application/node_modules/generator-templates-exploration/generators/app/index.js:90:21)

Is there a way to fix it or Canary is broken in that sense?

Best regards,
Ivan

**Comment by chgeo** [comment]
This seems to be resolved
